export const stringConstants={
    login:"Login",
    userNameandEmail:"Username or Email",
    pass:"password",
    orLoginWith:"or login with",
    google:"Google",
    facebook:"Facebook",
    newUser:"New User?",
    signUpNow:"Sign Up Now",
    register:"Register",
    iama:"I am a",
    student:"STUDENT",
    tutor:"TUTOR",
    userName:"Username",
    email:"Email",
    createAccount:"CREATE ACCOUNT",
    orSignUpWith:"or sign up with",
    alreadyAuser:"Already a User?",
    exploreOnLineCourse:"Explore Online Courses",
    onLineCourceTxt:"All Type of educational & professional courses available online",
    next:"Next",
    chooseCategories:"Choose Categories",
    continue:"CONTINUE",
    home:"Home",
    search:"Search",
    searchCategory:"Search for Topics, Courses & Educators",
    profile:"Profile",
    categories:"Categories",
    popularCource:"Popular Courses",
    seeAll:"See All",
    topSearch:"Top Search",
    browsingCategory:"Browse Categories",
    contactNumber:"Contact Number",
    pages:"Pages",
    newCourseNotification:"New Course Notification",
    studyReminder:"Study Reminder",
    mobileDesign:"Mobile Design",
    filter:"Filter",
    cancel:"Cancel",
    classType:"Class Type",
    classLevel:"Class Level",
    createdWith:"Created Within",
    classLength:"Class Length",
    reset:"Reset",
    apply:"Apply",
    chapter:"Chapter",
    files:"Files",
    discussion:"Discussion",
    aboutMe:"About Me",
    myCoures:"My Course",
    studentRating:"Student Rating",
    studentReview:"Student Review",
    connectHere:"Connect Here",
    memberShip:"MemberShip",
    unlimitedStudey:"Unlimited Study Anytime, Anywhere",
    choosePlan:"Choose a plan",
    notification:"Notification",
    nameEmailError:"Please enter your user name or email",
    passError:"Please enter your password",
    passFormatError:"Please enter valid password with 1 Capitol, 1 spacial and 1 Numeric character",
    userNameError:"Please enter user name",
    emailError:"Please enter your email",
    emailFormatError:"Please enter valid email",
    getStarted:"Get Started",
}